MedicalTestingSystem/config/routes.rb
Rails.application.routes.draw do
  get 'tests/show_results'
  post 'tests/show_results'
  get 'tests/finish_test'
  post 'tests/finish_test'
  resources :tests
  get 'orders/add_discount'
  post 'orders/add_discount'
  get 'orders/pay_order'
  post 'orders/pay_order'
  get 'orders/print_order'
  post 'orders/print_order'
  resources :orders
  get 'patients/search'
  post 'patients/search'
  get 'patients/add_patient_type'
  post 'patients/add_patient_type'
  get 'patients/remove_patient_type'
  post 'patients/remove_patient_type'
  resources :patients
  resources :patient_types
  resources :field_types
  get 'medteches' => 'medteches#index', :as => 'personnels'
  resources :medteches
  get 'test_types/search'
  post 'test_types/search'
  resources :test_types
  resources :test_fields
  resources :physicians
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations:  'users/registrations',
    passwords: 'users/passwords'
  }
  get 'users/create_user'
  post 'users/create_user'
  resources :users
  resources :roles
  get 'static/index'

  root to: 'static#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MedicalTestingSystem/app/models/edit_history.rb
class EditHistory < ApplicationRecord
  belongs_to :user
end

MedicalTestingSystem/app/models/field_type.rb
class FieldType < ApplicationRecord
  belongs_to :user
  has_many :test_fields, dependent: :destroy
end

MedicalTestingSystem/app/models/line.rb
class Line < ApplicationRecord
  belongs_to :user
  has_many :test_types, dependent: :destroy
end

MedicalTestingSystem/app/models/medtech.rb
class Medtech < ApplicationRecord
  belongs_to :user
end

MedicalTestingSystem/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :patient
  belongs_to :user
  has_many :tests, dependent: :destroy
end

MedicalTestingSystem/app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  has_many :patient_type_lookups, dependent: :destroy
  has_many :orders, dependent: :destroy
end

MedicalTestingSystem/app/models/patient_type.rb
class PatientType < ApplicationRecord
  belongs_to :user
  has_many :patient_type_lookups, dependent: :destroy
end

MedicalTestingSystem/app/models/physician.rb
class Physician < ApplicationRecord
  belongs_to :user
  has_many :test_types, dependent: :destroy
end

MedicalTestingSystem/app/models/role.rb
class Role < ApplicationRecord
  has_many :users, dependent: :destroy
end

MedicalTestingSystem/app/models/test.rb
class Test < ApplicationRecord
  belongs_to :test_type
  belongs_to :order
  belongs_to :user
  has_many :test_fields, dependent: :destroy
end

MedicalTestingSystem/app/models/test_field.rb
class TestField < ApplicationRecord
  belongs_to :test
  belongs_to :field_type
  belongs_to :user
end

MedicalTestingSystem/app/models/test_type.rb
class TestType < ApplicationRecord
  belongs_to :line
  belongs_to :user
  has_many :tests, dependent: :destroy
end

MedicalTestingSystem/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  has_many :edit_histories, dependent: :destroy
end

MedicalTestingSystem/app/helpers/medteches_helper.rb
module MedtechesHelper
end

MedicalTestingSystem/app/helpers/orders_helper.rb
module OrdersHelper
end

MedicalTestingSystem/app/helpers/patients_helper.rb
module PatientsHelper
end

MedicalTestingSystem/app/helpers/roles_helper.rb
module RolesHelper
end

MedicalTestingSystem/app/helpers/static_helper.rb
module StaticHelper
end

MedicalTestingSystem/app/helpers/tests_helper.rb
module TestsHelper
end

MedicalTestingSystem/app/helpers/users_helper.rb
module UsersHelper
end

MedicalTestingSystem/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Choice Health</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag "favicon.png" %>
  </head>

  <body>
    <% if current_user != nil %>
      <nav class="ui inverted blue vertical demo visible sidebar menu", id="navbar" data-no-turbolink>
        <%= link_to root_path, :class => "header item" do %>
          <%= image_tag "menu_logo_white.png" %>
        <% end %>
        <%= link_to root_path, :class => "item" do %>
          <i class="home icon"></i>
          Home
        <% end %>
        <%= link_to patients_path, :class => "item" do %>
          <i class="treatment icon"></i>
          Patients
        <% end %>
        <%= link_to test_types_path, :class => "item" do %>
          <i class="list icon"></i>
          Tests
        <% end %>
        <%= link_to field_types_path, :class => "item" do %>
          <i class="columns icon"></i>
          Test Fields
        <% end %>
        <% if current_user.role_id == @admin_id %>
          <%= link_to users_path, :class => "item" do %>
            <i class="user icon"></i>
            Users
          <% end %>

          <%= link_to personnels_path, :class => "item" do %>
            <i class="doctor icon"></i>
            Personnel
          <% end %>

          <%= link_to patient_types_path, :class => "item" do %>
            <i class="money icon"></i>
            Discounts
          <% end %>
        <% end %>
        <%= link_to destroy_user_session_path(current_user), method: "delete", :class => "item" do %>
          <i class="sign out icon"></i>
          Logout
        <% end %>
      </nav>
      <div class="pusher">
        <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>