MedicalTestingSystem/config/routes.rb
Rails.application.routes.draw do
  get 'tests/show_results'
  post 'tests/show_results'
  get 'tests/finish_test'
  post 'tests/finish_test'
  resources :tests
  get 'orders/add_discount'
  post 'orders/add_discount'
  get 'orders/pay_order'
  post 'orders/pay_order'
  get 'orders/print_order'
  post 'orders/print_order'
  resources :orders
  get 'patients/search'
  post 'patients/search'
  get 'patients/add_patient_type'
  post 'patients/add_patient_type'
  get 'patients/remove_patient_type'
  post 'patients/remove_patient_type'
  resources :patients
  resources :patient_types
  resources :field_types
  get 'medteches' => 'medteches#index', :as => 'personnels'
  resources :medteches
  get 'test_types/search'
  post 'test_types/search'
  resources :test_types
  resources :test_fields
  resources :physicians
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations:  'users/registrations',
    passwords: 'users/passwords'
  }
  get 'users/create_user'
  post 'users/create_user'
  resources :users
  resources :roles
  get 'static/index'

  root to: 'static#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MedicalTestingSystem/app/models/edit_history.rb
class EditHistory < ApplicationRecord
  belongs_to :user
end

MedicalTestingSystem/app/models/field_type.rb
class FieldType < ApplicationRecord
  belongs_to :user
  has_many :test_fields, dependent: :destroy
end

MedicalTestingSystem/app/models/line.rb
class Line < ApplicationRecord
  belongs_to :user
  has_many :test_types, dependent: :destroy
end

MedicalTestingSystem/app/models/medtech.rb
class Medtech < ApplicationRecord
  belongs_to :user
end

MedicalTestingSystem/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :patient
  belongs_to :user
  has_many :tests, dependent: :destroy
end

MedicalTestingSystem/app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  has_many :patient_type_lookups, dependent: :destroy
  has_many :orders, dependent: :destroy
end

MedicalTestingSystem/app/models/patient_type.rb
class PatientType < ApplicationRecord
  belongs_to :user
  has_many :patient_type_lookups, dependent: :destroy
end

MedicalTestingSystem/app/models/physician.rb
class Physician < ApplicationRecord
  belongs_to :user
  has_many :test_types, dependent: :destroy
end

MedicalTestingSystem/app/models/role.rb
class Role < ApplicationRecord
  has_many :users, dependent: :destroy
end

MedicalTestingSystem/app/models/test.rb
class Test < ApplicationRecord
  belongs_to :test_type
  belongs_to :order
  belongs_to :user
  has_many :test_fields, dependent: :destroy
end

MedicalTestingSystem/app/models/test_field.rb
class TestField < ApplicationRecord
  belongs_to :test
  belongs_to :field_type
  belongs_to :user
end

MedicalTestingSystem/app/models/test_type.rb
class TestType < ApplicationRecord
  belongs_to :line
  belongs_to :user
  has_many :tests, dependent: :destroy
end

MedicalTestingSystem/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  has_many :edit_histories, dependent: :destroy
end

MedicalTestingSystem/app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /physicians
  # GET /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1
  # GET /physicians/1.json
  def show
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
  end

  # GET /physicians/1/edit
  def edit
  end

  # POST /physicians
  # POST /physicians.json
  def create
    params[:physician][:user_id] = current_user.id
    @physician = Physician.new(params[:physician].permit(:first_name, :middle_name, :last_name, :prefix, :suffix, :user_id))

    respond_to do |format|
      if @physician.save
        format.html { redirect_to personnels_path, notice: 'Physician was successfully created.' }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1
  # PATCH/PUT /physicians/1.json
  def update
    params[:physician][:user_id] = current_user.id
    respond_to do |format|
      if @physician.update(params[:physician].permit(:first_name, :middle_name, :last_name, :prefix, :suffix, :user_id))
        format.html { redirect_to personnels_path, notice: 'Physician was successfully updated.' }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1
  # DELETE /physicians/1.json
  def destroy
    @physician.destroy
    respond_to do |format|
      format.html { redirect_to personnels_url, notice: 'Physician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physician_params
      params.require(:physician).permit(:first_name, :middle_name, :last_name, :prefix, :suffx, :user_id)
    end
end

MedicalTestingSystem/app/helpers/medteches_helper.rb
module MedtechesHelper
end

MedicalTestingSystem/app/helpers/orders_helper.rb
module OrdersHelper
end

MedicalTestingSystem/app/helpers/patients_helper.rb
module PatientsHelper
end

MedicalTestingSystem/app/helpers/physicians_helper.rb
module PhysiciansHelper
end

MedicalTestingSystem/app/helpers/roles_helper.rb
module RolesHelper
end

MedicalTestingSystem/app/helpers/static_helper.rb
module StaticHelper
end

MedicalTestingSystem/app/helpers/test_types_helper.rb
module TestTypesHelper
end

MedicalTestingSystem/app/helpers/tests_helper.rb
module TestsHelper
end

MedicalTestingSystem/app/helpers/users_helper.rb
module UsersHelper
end

MedicalTestingSystem/app/views/physicians/_form.html.erb
<%= form_for(physician, :html => {:class => "ui blue form segment"}) do |f| %>
  <% if physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
      <% physician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3 class="ui blue header">Name</h3>
  <div class="three fields">
    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>

    <div class="field">
      <%= f.label :middle_name %>
      <%= f.text_field :middle_name %>
    </div>

    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
  </div>

  <h3 class="ui blue header">Title</h3>
  <div class="two fields">
    <div class="field">
      <%= f.label :prefix %>
      <%= f.text_field :prefix %>
    </div>

    <div class="field">
      <%= f.label :suffix %>
      <%= f.text_field :suffix %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Submit', :class => "ui button" %>
  </div>
<% end %>

MedicalTestingSystem/app/views/physicians/edit.html.erb
<h1 class="ui blue header">
  <%= link_to 'Back', personnels_path, :class => "ui right floated button" %>
  Editing Physician
</h1>

<%= render 'form', physician: @physician %>

MedicalTestingSystem/app/views/physicians/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Physicians</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Prefix</th>
      <th>Suffx</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @physicians.each do |physician| %>
      <tr>
        <td><%= physician.first_name %></td>
        <td><%= physician.middle_name %></td>
        <td><%= physician.last_name %></td>
        <td><%= physician.prefix %></td>
        <td><%= physician.suffx %></td>
        <td><%= physician.user %></td>
        <td><%= link_to 'Show', physician %></td>
        <td><%= link_to 'Edit', edit_physician_path(physician) %></td>
        <td><%= link_to 'Destroy', physician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Physician', new_physician_path %>

MedicalTestingSystem/app/views/physicians/new.html.erb
<h1 class="ui blue header">
  <%= link_to 'Back', personnels_path, :class => "ui right floated button" %>
  New Physician
</h1>

<%= render 'form', physician: @physician %>

MedicalTestingSystem/app/views/physicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @physician.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @physician.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @physician.last_name %>
</p>

<p>
  <strong>Prefix:</strong>
  <%= @physician.prefix %>
</p>

<p>
  <strong>Suffx:</strong>
  <%= @physician.suffx %>
</p>

<p>
  <strong>User:</strong>
  <%= @physician.user %>
</p>

<%= link_to 'Edit', edit_physician_path(@physician) %> |
<%= link_to 'Back', physicians_path %>