MedicalTestingSystem/config/routes.rb
Rails.application.routes.draw do
  get 'tests/show_results'
  post 'tests/show_results'
  get 'tests/finish_test'
  post 'tests/finish_test'
  resources :tests
  get 'orders/add_discount'
  post 'orders/add_discount'
  get 'orders/pay_order'
  post 'orders/pay_order'
  get 'orders/print_order'
  post 'orders/print_order'
  resources :orders
  get 'patients/search'
  post 'patients/search'
  get 'patients/add_patient_type'
  post 'patients/add_patient_type'
  get 'patients/remove_patient_type'
  post 'patients/remove_patient_type'
  resources :patients
  resources :patient_types
  resources :field_types
  get 'medteches' => 'medteches#index', :as => 'personnels'
  resources :medteches
  get 'test_types/search'
  post 'test_types/search'
  resources :test_types
  resources :test_fields
  resources :physicians
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations:  'users/registrations',
    passwords: 'users/passwords'
  }
  get 'users/create_user'
  post 'users/create_user'
  resources :users
  resources :roles
  get 'static/index'

  root to: 'static#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MedicalTestingSystem/app/models/edit_history.rb
class EditHistory < ApplicationRecord
  belongs_to :user
end

MedicalTestingSystem/app/models/field_type.rb
class FieldType < ApplicationRecord
  belongs_to :user
  has_many :test_fields, dependent: :destroy
end

MedicalTestingSystem/app/models/line.rb
class Line < ApplicationRecord
  belongs_to :user
  has_many :test_types, dependent: :destroy
end

MedicalTestingSystem/app/models/medtech.rb
class Medtech < ApplicationRecord
  belongs_to :user
end

MedicalTestingSystem/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :patient
  belongs_to :user
  has_many :tests, dependent: :destroy
end

MedicalTestingSystem/app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  has_many :patient_type_lookups, dependent: :destroy
  has_many :orders, dependent: :destroy
end

MedicalTestingSystem/app/models/patient_type.rb
class PatientType < ApplicationRecord
  belongs_to :user
  has_many :patient_type_lookups, dependent: :destroy
end

MedicalTestingSystem/app/models/physician.rb
class Physician < ApplicationRecord
  belongs_to :user
  has_many :test_types, dependent: :destroy
end

MedicalTestingSystem/app/models/role.rb
class Role < ApplicationRecord
  has_many :users, dependent: :destroy
end

MedicalTestingSystem/app/models/test.rb
class Test < ApplicationRecord
  belongs_to :test_type
  belongs_to :order
  belongs_to :user
  has_many :test_fields, dependent: :destroy
end

MedicalTestingSystem/app/models/test_field.rb
class TestField < ApplicationRecord
  belongs_to :test
  belongs_to :field_type
  belongs_to :user
end

MedicalTestingSystem/app/models/test_type.rb
class TestType < ApplicationRecord
  belongs_to :line
  belongs_to :user
  has_many :tests, dependent: :destroy
end

MedicalTestingSystem/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  has_many :edit_histories, dependent: :destroy
end

MedicalTestingSystem/app/controllers/medteches_controller.rb
class MedtechesController < ApplicationController
  before_action :set_medtech, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /medteches
  # GET /medteches.json
  def index
    @medteches = Medtech.all
    @physicians = Physician.all
  end

  # GET /medteches/1
  # GET /medteches/1.json
  def show
  end

  # GET /medteches/new
  def new
    @medtech = Medtech.new
  end

  # GET /medteches/1/edit
  def edit
  end

  # POST /medteches
  # POST /medteches.json
  def create
    params[:medtech][:user_id] = current_user.id
    @medtech = Medtech.new(medtech_params)

    respond_to do |format|
      if @medtech.save
        format.html { redirect_to personnels_path, notice: 'Medtech was successfully created.' }
        format.json { render :show, status: :created, location: @medtech }
      else
        format.html { render :new }
        format.json { render json: @medtech.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medteches/1
  # PATCH/PUT /medteches/1.json
  def update
    params[:medtech][:user_id] = current_user.id
    respond_to do |format|
      if @medtech.update(medtech_params)
        format.html { redirect_to personnels_path, notice: 'Medtech was successfully updated.' }
        format.json { render :show, status: :ok, location: @medtech }
      else
        format.html { render :edit }
        format.json { render json: @medtech.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medteches/1
  # DELETE /medteches/1.json
  def destroy
    @medtech.destroy
    respond_to do |format|
      format.html { redirect_to personnels_url, notice: 'Medtech was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medtech
      @medtech = Medtech.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medtech_params
      params.require(:medtech).permit(:first_name, :middle_name, :last_name, :user_id)
    end
end

MedicalTestingSystem/app/helpers/medteches_helper.rb
module MedtechesHelper
end

MedicalTestingSystem/app/helpers/orders_helper.rb
module OrdersHelper
end

MedicalTestingSystem/app/helpers/patients_helper.rb
module PatientsHelper
end

MedicalTestingSystem/app/helpers/physicians_helper.rb
module PhysiciansHelper
end

MedicalTestingSystem/app/helpers/roles_helper.rb
module RolesHelper
end

MedicalTestingSystem/app/helpers/static_helper.rb
module StaticHelper
end

MedicalTestingSystem/app/helpers/test_types_helper.rb
module TestTypesHelper
end

MedicalTestingSystem/app/helpers/tests_helper.rb
module TestsHelper
end

MedicalTestingSystem/app/helpers/users_helper.rb
module UsersHelper
end

MedicalTestingSystem/app/views/medteches/_form.html.erb
<%= form_for(medtech, :html => {:class => "ui blue form segment"}) do |f| %>
  <% if medtech.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medtech.errors.count, "error") %> prohibited this medtech from being saved:</h2>

      <ul>
      <% medtech.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="three fields">
    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>

    <div class="field">
      <%= f.label :middle_name %>
      <%= f.text_field :middle_name %>
    </div>

    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Submit', :class => "ui button" %>
  </div>
<% end %>

MedicalTestingSystem/app/views/medteches/edit.html.erb
<h1 class="ui blue header">
  <%= link_to 'Back', personnels_path, :class => "ui right floated button" %>
  Editing Medtech
</h1>

<%= render 'form', medtech: @medtech %>

MedicalTestingSystem/app/views/medteches/index.html.erb
<h1 class="ui blue header">
  <%= link_to 'New Medtech', new_medtech_path, :class => "ui right floated button" %>
  Medteches
</h1>

<table class="ui blue selectable striped celled table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Created by</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @medteches.each do |medtech| %>
      <tr>
        <td><%= medtech.first_name %> <%= medtech.middle_name %> <%= medtech.last_name %></td>
        <td><%= medtech.user.first_name %> <%= medtech.user.last_name %></td>
        <td class="center aligned">
          <%= link_to edit_medtech_path(medtech), :class => "ui blue button" do %>
            <i class="edit icon"></i>
            Edit
          <% end %>
        </td>
        <td class="center aligned">
          <%= link_to medtech, method: :delete, data: { confirm: 'Are you sure?' }, :class => "ui red button" do %>
            <i class="delete icon"></i>
            Delete
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1 class="ui blue header">
  <%= link_to 'New Physician', new_physician_path, :class => "ui right floated button" %>
  Physicians
</h1>

<table class="ui blue selectable striped celled table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Created by</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @physicians.each do |physician| %>
      <tr>
        <td><%= physician.prefix %> <%= physician.first_name %> <%= physician.middle_name %> <%= physician.last_name %>
          <% if physician.suffix != nil %>
           , <%= physician.suffix %>
          <% end %>
        </td>
        <td><%= physician.user.first_name %> <%= physician.user.last_name %></td>
        <td class="center aligned">
          <%= link_to edit_physician_path(physician), :class => "ui blue button" do %>
            <i class="edit icon"></i>
            Edit
          <% end %>
        </td>
        <td class="center aligned">
          <%= link_to physician, method: :delete, data: { confirm: 'Are you sure?' }, :class => "ui red button" do %>
            <i class="delete icon"></i>
            Delete
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

MedicalTestingSystem/app/views/medteches/new.html.erb
<h1 class="ui blue header">
  <%= link_to 'Back', personnels_path, :class => "ui right floated button" %>
  New Medtech
</h1>

<%= render 'form', medtech: @medtech %>

MedicalTestingSystem/app/views/medteches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @medtech.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @medtech.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @medtech.last_name %>
</p>

<p>
  <strong>User:</strong>
  <%= @medtech.user %>
</p>

<%= link_to 'Edit', edit_medtech_path(@medtech) %> |
<%= link_to 'Back', personnels_path %>